### ISSUE TITLE
Production database backups

### ISSUE THREAD

**Issue by DominicRoyStang** [BlockedTODO/BlockedTODO#130]
Will need a storage bucket and a cron job that does a pg_dump, and stores the dump in the bucket.

Can either use this package: https://github.com/smooth-code/knex-scripts or just a bash script.

---

Checklist

- [x] There is a storage bucket for the backups
- [x] There is a backup script
- [x] Secret is updated (`is_production: true` was replaced with `environment: "production"`)
- [x] There is a cron job (visible as a k8s workload)

**Comment by DominicRoyStang** [comment]
For now, knex-scripts isn't an option because the dumps only export the schema.
I logged an issue on their repo: https://github.com/smooth-code/knex-scripts/issues/11

We'll see if we get a response.

**Comment by DominicRoyStang** [comment]
For the backup script, I need to have a service account that allows me to upload the backups (as per https://cloud.google.com/storage/docs/reference/libraries#setting_up_authentication)

The best way to share that service account with the running application would be to use k8s secrets. See this guide: https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform#3_manage_service_account_credentials_using_secrets

**Comment by DominicRoyStang** [comment]
Example k8s cron job

```yaml
{{$label := .Values.database_backup.label}}
{{$secrets := .Values.database_backup.secrets}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: {{$label}}-cronjob
    namespace: {{.Values.namespace}}
spec:
    schedule: "0 3 * * *"
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 2
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: OnFailure
                    containers:
                      - name: database-backup
                        image: {{.Values.database_backup.image}}
                        imagePullPolicy: IfNotPresent
                        env:
                          - name: IS_PRODUCTION
                            value: {{.Values.is_production | squote}}
                          - name: NAMESPACE
                            value: {{.Values.namespace}}
                          - name: BACKUP_BUCKET
                            value: {{.Values.database_backup.bucket_name}}
```
