### ISSUE TITLE
Update k8s version to >1.23.x

### ISSUE THREAD

**Issue by DominicRoyStang** [BlockedTODO/BlockedTODO#424]
Kubernetes will be dropping support for dockershim. Containerd will still be supported so images built by Docker should still work fine. I don't expect anything to break but I'll try to be on high alert an monitor things attentively after the upgrade.

This upgrade also shouldn't affect Minikube or Docker Desktop.

This video gives a good overview of the changes and their impacts: https://www.youtube.com/watch?v=7KUdmFyefSA

Starting at version 1.20, a single warning log will be output, and support will be completely removed at version 1.23 in late 2021.

**Comment by DominicRoyStang** [comment]
When 1.18 is in stable on Google Cloud Platform, I'll be able to address the BlockedTODO comment for HTTPS redirect by adding this to `ingress.yaml`

```yaml
---

# For HTTPS redirects, as per https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect
{{- if eq .Values.environment "production"}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
    name: blockedtodo-frontend-config
    namespace: {{.Values.namespace}}
spec:
    redirectToHttps:
        enabled: true
{{- end}}
```

And also adding this annotation to the ingress CDE `networking.gke.io/v1beta1.FrontendConfig: blockedtodo-frontend-config`
